const fmt=n=>new Intl.NumberFormat('ru-KZ').format(n)+' ₸';
const cats={expense:['Продукты','Такси','Кафе и рестораны','Развлечения','Мобильная связь','Бензин','Лекарства','Кредиты','Коммунальные','Подписки','Покупки'],income:['Зарплата','Подработка','Кэшбэк','Другое']};
const icons={'Продукты':'🛒','Такси':'🚕','Кафе и рестораны':'☕','Развлечения':'🎬','Мобильная связь':'📱','Бензин':'⛽','Лекарства':'💊','Кредиты':'🏦','Коммунальные':'🏠','Подписки':'✦','Покупки':'🛍️','Зарплата':'💼','Подработка':'✳️','Кэшбэк':'↩️','Другое':'•'};
const defaults={transactions:[
 {id:1,type:'income',amount:128000,category:'Зарплата',description:'Доход Анары',member:'Анара',date:'Сегодня'},
 {id:2,type:'expense',amount:1850,category:'Продукты',description:'ВкусВилл',member:'Анара',date:'Сегодня'},
 {id:3,type:'expense',amount:476,category:'Такси',description:'Яндекс Go',member:'Нурсултан',date:'Вчера'},
 {id:4,type:'expense',amount:1290,category:'Мобильная связь',description:'МТС',member:'Нурсултан',date:'Вчера'},
 {id:5,type:'income',amount:142000,category:'Зарплата',description:'Доход Нурсултана',member:'Нурсултан',date:'20 августа'},
 {id:6,type:'expense',amount:48000,category:'Кредиты',description:'Платёж по ипотеке',member:'Анара',date:'18 августа'},
 {id:7,type:'expense',amount:6200,category:'Бензин',description:'Газпромнефть',member:'Нурсултан',date:'16 августа'},
 {id:8,type:'expense',amount:22400,category:'Продукты',description:'Пятёрочка и рынок',member:'Анара',date:'14 августа'},
 {id:9,type:'expense',amount:8900,category:'Коммунальные',description:'Квартплата',member:'Нурсултан',date:'10 августа'}],goals:[{id:1,title:'Путешествие в Японию',target:350000,saved:128000,icon:'✈️'},{id:2,title:'Первый взнос на квартиру',target:1500000,saved:420000,icon:'🏠'},{id:3,title:'Депозит',target:300000,saved:86000,icon:'🌿'}]};
let data=JSON.parse(localStorage.getItem('together-save-data')||'null')||defaults, activeFilter='all',transType='expense',editTransactionId=null,editGoalId=null;
if(!data.membersRenamed){data.transactions.forEach(t=>{if(t.member==='Анна')t.member='Анара';if(t.member==='Михаил')t.member='Нурсултан';if(t.description==='Зарплата Анны')t.description='Доход Анары';if(t.description==='Зарплата Михаила')t.description='Доход Нурсултана'});data.membersRenamed=true;localStorage.setItem('together-save-data',JSON.stringify(data));}
const save=()=>localStorage.setItem('together-save-data',JSON.stringify(data));
const sum=(type,arr=data.transactions)=>arr.filter(x=>x.type===type).reduce((s,x)=>s+x.amount,0);
const transactionMarkup=t=>`<article class="transaction"><span class="trans-icon">${icons[t.category]||'•'}</span><div><strong>${t.description}</strong><small>${t.category} · ${t.member} · ${t.date}</small></div><span class="amount ${t.type}">${t.type==='expense'?'−':'+'}${fmt(t.amount)}</span><button class="edit-button" data-edit-transaction="${t.id}" aria-label="Редактировать операцию">✎</button></article>`;
const goalMarkup=g=>{const p=Math.min(100,Math.round(g.saved/g.target*100));return `<article class="goal-card"><span class="goal-icon">${g.icon}</span><div><strong>${g.title}</strong><p>${fmt(g.saved)} из ${fmt(g.target)} · ${p}%</p><div class="mini-progress"><i style="width:${p}%"></i></div></div><button class="edit-button" data-edit-goal="${g.id}" aria-label="Редактировать цель">✎</button></article>`};
function render(){const income=sum('income'),expense=sum('expense'),saved=data.goals.reduce((s,g)=>s+g.saved,0), available=Math.max(0,income-expense-Math.round(income*.1));document.querySelector('#incomeAmount').textContent=fmt(income);document.querySelector('#expenseAmount').textContent=fmt(expense);document.querySelector('#availableAmount').textContent=fmt(available);document.querySelector('#savedAmount').textContent=fmt(saved);const percent=Math.min(100,Math.round(saved/2150000*100));document.querySelector('#savingsPercent').textContent=percent+'%';document.querySelector('#savingsProgress').style.width=percent+'%';document.querySelector('#goalsPreview').innerHTML=data.goals.slice(0,2).map(goalMarkup).join('');document.querySelector('#goalsFull').innerHTML=data.goals.map(goalMarkup).join('');document.querySelector('#recentTransactions').innerHTML=data.transactions.slice(0,4).map(transactionMarkup).join('');const shown=activeFilter==='all'?data.transactions:data.transactions.filter(x=>x.type===activeFilter);document.querySelector('#transactionsList').innerHTML=shown.map(transactionMarkup).join('');renderAnalytics(expense);}
function renderAnalytics(total){const by={};data.transactions.filter(x=>x.type==='expense').forEach(x=>by[x.category]=(by[x.category]||0)+x.amount);const top=Object.entries(by).sort((a,b)=>b[1]-a[1]).slice(0,5);document.querySelector('#chartTotal').textContent=fmt(total);document.querySelector('#categoryChart').innerHTML=top.map(([n,v])=>`<div class="chart-row"><span>${icons[n]} ${n}</span><div class="bar"><i style="width:${Math.round(v/total*100)}%"></i></div><b>${fmt(v)}</b></div>`).join('');let food=by['Продукты']||0;document.querySelector('#insightText').textContent=food?`Продукты — самая заметная статья: ${fmt(food)}. План покупок на неделю поможет сохранить часть бюджета.`:'Добавьте расходы, и я покажу полезные наблюдения.';const members=['Нурсултан','Анара'];document.querySelector('#memberStats').innerHTML=members.map(m=>`<article><p>${m}</p><strong>${fmt(sum('expense',data.transactions.filter(x=>x.member===m)))}</strong><p>расходы</p></article>`).join('');}
function setType(type){transType=type;document.querySelectorAll('.toggle-choice').forEach(b=>b.classList.toggle('selected',b.dataset.type===type));const options=[...new Set([...cats[type],...data.transactions.filter(x=>x.type===type).map(x=>x.category)])];document.querySelector('#categoryOptions').innerHTML=options.map(c=>`<option value="${c}">`).join('');}
document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>{const n=b.dataset.nav;document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id==='screen-'+n));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.nav===n));window.scrollTo(0,0)}));
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()}));
function openTransaction(item){editTransactionId=item?.id||null;const f=document.querySelector('#transactionForm');f.reset();setType(item?.type||'expense');if(item){f.amount.value=item.amount;f.description.value=item.description;f.member.value=item.member;f.category.value=item.category;}document.querySelector('#transactionDialog h2').textContent=item?'Редактировать операцию':'Новая операция';document.querySelector('#transactionDialog').showModal()}
function openGoal(item){editGoalId=item?.id||null;const f=document.querySelector('#goalForm');f.reset();if(item){f.title.value=item.title;f.target.value=item.target;f.saved.value=item.saved;}document.querySelector('#goalDialog h2').textContent=item?'Редактировать цель':'Новая цель';document.querySelector('#goalDialog').showModal()}
document.querySelector('#openTransaction').onclick=()=>openTransaction();document.querySelector('#openGoal').onclick=()=>openGoal();document.addEventListener('click',e=>{const t=e.target.closest('[data-edit-transaction]'),g=e.target.closest('[data-edit-goal]');if(t)openTransaction(data.transactions.find(x=>x.id===+t.dataset.editTransaction));if(g)openGoal(data.goals.find(x=>x.id===+g.dataset.editGoal));});document.querySelector('#saveMoneyButton').onclick=()=>{document.querySelector('#screen-home').classList.remove('active');document.querySelector('#screen-goals').classList.add('active');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.nav==='goals'))};document.querySelectorAll('.toggle-choice').forEach(b=>b.onclick=()=>setType(b.dataset.type));
document.querySelector('#transactionForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const f=new FormData(e.target),record={id:editTransactionId||Date.now(),type:transType,amount:+f.get('amount'),category:f.get('category'),description:f.get('description'),member:f.get('member'),date:editTransactionId?data.transactions.find(x=>x.id===editTransactionId).date:'Сегодня'};if(editTransactionId)data.transactions=data.transactions.map(x=>x.id===editTransactionId?record:x);else data.transactions.unshift(record);save();render();});document.querySelector('#goalForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const f=new FormData(e.target),record={id:editGoalId||Date.now(),title:f.get('title'),target:+f.get('target'),saved:+f.get('saved'),icon:editGoalId?data.goals.find(x=>x.id===editGoalId).icon:'🎯'};if(editGoalId)data.goals=data.goals.map(x=>x.id===editGoalId?record:x);else data.goals.push(record);save();render();});
document.querySelector('#memberButton').onclick=()=>alert('Семья: Анна и Михаил\n\nПодключение карт появится здесь. Для реальных банковских операций понадобится защищённая интеграция с банковским API или агрегатором.');setType('expense');render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
